[workspace]
members = [
    "contract",
    "contract/crates/resolvers/time_window_resolver",
    "contract/crates/resolvers/price_threshold_resolver",
    "contract/crates/resolvers/token_balance_resolver",
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true