coverage:
  precision: 2
  round: down
  range:
    - 70
    - 100

comment:

  layout: "reach, diff, flags, tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "node_modules"
  - "coverage"
  - "dist"
  - "build"
  - "**/*.d.ts"
  - "**/fuzz/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"

flags:
  rust:
    carryforward: true
    paths:
      - contract
  frontend:
    carryforward: true
    paths:
      - frontend

status:
  project: true
  patch: true
  changes: false
  
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no